### ISSUE TITLE
tutorial.ipynb broken with lagrangebench==0.0.2

### ISSUE THREAD

**Issue by fuersta** [tumaer/lagrangebench#19]
Dear authors,

it seems that the tutorial notebook is not working anymore after the recent commit.
The parameters for e.g. the dataset have changed (inclusion of `extra_seq_length`).
Will you release a 0.0.3 to account for this changes?

Thanks in advance!

Best,
Andreas

**Comment by arturtoshev** [comment]
Dear Andreas,

first, thank you for using the codebase! 

We recently made a few changes and there are two more PRs on the way before we make the new release (one PR with more unit tests and one with a batched inference loop), but running the tutorial notebook should be fine as is. I just did the following and the `notebooks/tutorial.ipynb` ran through:

```bash
git clone https://github.com/tumaer/lagrangebench.git
cd lagrangebench
poetry install
# and now run notebooks/tutorial.ipynb
```

Could you give us some more details on what didn't work on your side?

Best,
Artur

**Comment by fuersta** [comment]
Dear Artur,

thanks for hinting me to `poetry`, installing the dependencies with it works fine.
I was installing with `pip`, and there the new version was not available in PyPI.

Wishing you a happy new year 2024!

Best,
Andreas
